# -*- coding: utf-8 -*-
"""data mining assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-BZ_mcYZsaoru_S70YvCDWKQEVPAHOdt
"""

import pandas as pd
import numpy as np

#loading files
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
gender = pd.read_csv("gender_submission.csv")  # has 'Survived' for test set

# adding Survived column to test set

test = test.merge(gender, on='PassengerId', how='left')

# Combining datasets

combined = pd.concat([train, test], ignore_index=True, sort=False)

# Extracting Title from Name

combined['Title'] = combined['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)

# Data Cleaning

# Filling missing Age with mean
combined['Age'] = combined['Age'].fillna(combined['Age'].mean())


# Filling missing Fare with mean
combined['Fare'] = combined['Fare'].fillna(combined['Fare'].mean())

# Filling missing Embarked with most common value
combined['Embarked'] = combined['Embarked'].fillna(combined['Embarked'].mode()[0])

# Droping Cabin
if 'Cabin' in combined.columns:
    combined.drop(columns=['Cabin'], inplace=True)

# Handling Noisy Data

bins = [0, 12, 18, 35, 60, np.inf]
labels = ['Child', 'Teen', 'Young Adult', 'Adult', 'Senior']
combined['AgeGroup'] = pd.cut(combined['Age'], bins=bins, labels=labels)


print(combined[['Age', 'AgeGroup']].head())

#Saved Cleaned Combined Dataset

combined.to_csv("titanic_merged_preprocessed.csv", index=False)

# Final dataset info
print("Final Merged Dataset Info:\n")
print(combined.info())